### ISSUE TITLE
Allow properties to have a default value

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Fame#18]
To avoid properties evaluated as nil when it does not make sense, or nil checks like 
```smalltalk 
isClassSide
    ^ classSide ifNil: [ ^ false ]
```

---> create ```FmxMBBehavior>#property:type:defaultValue:```

**Comment by NicolasAnquetil** [comment]
seems more a Famix issue to handle in generator: https://github.com/moosetechnology/Famix/issues/228
